[project]
name = "tsgam_estimator"
version = "0.1.1"
description = "Time series GAM (Generalized Additive Model) estimators for load forecasting"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "spcqe",
    "pandas"
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]
docs = [
    "sphinx>=8.0.0",
    "sphinx-rtd-theme>=3.0.0",
    "myst-parser>=3.0.0",
]

[build-system]
requires = ["uv_build>=0.9.23,<0.10.0"]
build-backend = "uv_build"


[tool.coverage.run]
relative_files = true
source = ["src/tsgam_estimator"]
